### PR TITLE
partial fix for #2

### PR DESCRIPTION
**Pull request by simonsd**
Hi,

Sorry, but I couldn't find a way to attach commits to the issue I created,
so I decided to simply make a pull request.

This patch checks wether an alternate port is specified in the gitServer param and adjusts the clone url boxes accordingly.
Sadly I haven't yet found a way to do the same with the git instructions template for empty repos.
It's also most likely not the cleanest solutions, but it works.
Any thoughts?

Signed-off-by: Dave Simons dave@inuits.eu

### CODE REVIEW

**Comment by kubitron** [comment]
Thanks.   I'll take a look into this very shortly.

Sorry for the delay -- I've been dealing with beginning of term.

**Comment by simonsd** [comment]
no worries, I think you're still pretty active :)
I also forgot about the actual cloning of the gitolite-admin repo,
so I'm looking into that now.

**Comment by kubitron** [comment]
On 1/24/2012 3:25 PM, Dave Simons wrote:

> no worries, I think you're still pretty active :)
> I also forgot about the actual cloning of the gitolite-admin repo,
> so I'm looking into that now.
> 
> Thanks.

Your description of what you did was quite good (on the original issue 
report).  I'll be able to replicate it without problems.  I'll do it, 
because I need to update the README and possibly the validation code.

Are you running from my master branch with the path-rationalization 
commits yet?

--KUBI--

## 

Professor John Kubiatowicz
673 Soda Hall
Berkeley, CA 94720

**Comment by simonsd** [comment]
Yeah, this is running on top of your latest commits.
I noticed some extra settings pop up last time I played around with it,
but since we're in the progress of migration our production redmine I didn't feel like taking the risk.
They have now moved the deadline back a few days, so I'm trying to get things cleaned up and redeployed before that.

My attempts so far at adjusting the url used for cloning the gitolite-admin repo are pretty futile.
I'm just breaking the testing setup right now ..
Good news is that the breakage is due to my playing around, not your commits,
so I'll be pulling those into our production setup in the morning.
Haven't seen any problems with them yet, but I must say I haven't used them much yet either.
I'll let you know if anything comes up.

**Comment by kubitron** [comment]
On 1/24/2012 4:13 PM, Dave Simons wrote:

> Yeah, this is running on top of your latest commits.
> I noticed some extra settings pop up last time I played around with it,
> but since we're in the progress of migration our production redmine I didn't feel like taking the risk.
> They have now moved the deadline back a few days, so I'm trying to get things cleaned up and redeployed before that.
> 
> My attempts so far at adjusting the url used for cloning the gitolite-admin repo are pretty futile.
> I'm just breaking the testing setup right now ..
> Good news is that the breakage is due to my playing around, not your commits,
> so I'll be pulling those into our production setup in the morning.
> Haven't seen any problems with them yet, but I must say I haven't used them much yet either.
> I'll let you know if anything comes up.
> 
> Make sure that you run "rake db:migrate_plugins".  Extra settings can be 
> ignored for now.

I'll take a stab at your feature request as soon as a get a chance...

--KUBI--

## 

Professor John Kubiatowicz
673 Soda Hall
Berkeley, CA 94720

**Comment by kubitron** [comment]
Just to clarify -- what is failing for you?  I thought you had altered the two "git clone" lines in git_hosting.rb and that worked for you...?

Incidentally, one thing that you definitely get with the latest commits is that the admin has a "public key" screen for users and can thus help them with their key uploads... (found this useful for more clueless users).

**Comment by simonsd** [comment]
Yes I did indeed adjust those url's, however those were just simple hardcoded fixes.
If I were to use a gitServer param without a ':port' suffix, the url's would not work.

What is failing is an if-statement I put in, that should check wether a ':port' suffix is specified, and then adjust the url.
However I don't know ruby, so I'm just stumbling about a bit.

Once that's done, it's only the git_introduction page that needs adjusting.
Iirc that is being created with ruby/erb as well, so perhaps the previous fix could be ported.

As for the 'public key' screen for users, didn't notice that at all yet.
Just took a look and it does indeed seem promising.

**Comment by kubitron** [comment]
Ok.  Check out the 'testing' branch.  Hopefully it will do what you need...

**Comment by simonsd** [comment]
works like a charm.
closing the pull request since you're testing branch fixes my problems.

**Pull request closed without merging**
