### PR TITLE
Fix an error that occurs while uninstalling from DB

### PR DESCRIPTION
**Pull request by crocket**
2011072600000_extend_changesets_notified_cia.rb tries to delete
notified_cia column in changesets table, but
2011081700000_move_notified_cia_to_git_cia_notifications.rb deletes
notified_cia column before it does, so an error occurs.

A solution is to let 2011072600000_extend_changesets_notified_cia.rb
remove notified_cia column only if the column exists.

### CODE REVIEW

**Comment by crocket** [comment]
I use PostgreSQL 9.1.4.

I tried to remove redmine_git_hosting from my system because I wanted more fine-grained control.
And I removed it.

But it is needed yet for my company since non-technical people will use chiliproject.

**Comment by kubitron** [comment]
Sorry about that. PostgresSQL 9x has been causing problems with migrations.  Thanks for catching that one.

What sort of finer-grain would you like?

**Comment by crocket** [comment]
The repo name has to match the project identifer name in redmine_git_hosting.
Since project identifier names has to be unique among all projects, I couldn't use proper repo names for my git projects.

For example, git@localhost:elisa/home/elisa/ssh wouldn't be allowed since a subproject can't have a name elisa because the top level project has taken the name.

I want repo names to be independent of project identifiers.

**Comment by kubitron** [comment]
On 11/21/2012 4:33 PM, crocket wrote:

> The repo name has to match the project identifer name in 
> redmine_git_hosting.
> Since project identifier names has to be unique among all projects, I 
> couldn't use proper repo names for my git projects.
> 
> For example, git@localhost:elisa/home/elisa/ssh wouldn't be allowed 
> since a subproject can't have a name elisa because the top level 
> project has taken the name.
> 
> I want repo names to be separate from project identifiers.
> 
> If you install Redmine 1.4, this is much better, since you can have 
> multiple repos/project (and name them what you like).  The plugin now 
> supports this.

--KUBI--

## 

Professor John Kubiatowicz
673 Soda Hall
Berkeley, CA 94720

**Comment by crocket** [comment]
Does redmine_git_hosting allow creating repositories with different names than project identifiers?

**Comment by kubitron** [comment]
Yes.  The path has to have the project name in it as a parent, but the name is configurable (and must be unique from project names, but otherwise completely flexible).  This is only with Redmine 1.4+ (and not currently Redmine 2.0, since I haven't quite ported it yet).

**Comment by crocket** [comment]
Is it ok for me to create a feature request asking for repository names completely independent of project identifiers or names?

**Comment by kubitron** [comment]
Sure.  Do you mean other than what I've described above?  Or, do you mean the Redmine 1.4 functionality for Chili?

**Comment by crocket** [comment]
You said "The path has to have the project name in it as a parent, but the name is configurable (and must be unique from project names, but otherwise completely flexible). This is only with Redmine 1.4+"
But I want repo paths and names to be completely independent of project names and identifiers.

The paths don't have to have the project name in it as a parent in my opinion.

You could suggest such a repo name and path by auto completion, but it should let users choose their own repo names and paths.

**Comment by kubitron** [comment]
I see. Complete independence is probably not going to happen soon, since tying the project name to the repos helps make the repository repairable/recoverable if something happens during Redmine/Chili repository manipulations.  Making the names independent would change a lot of code in the current plugin...

**Pull request merged**
